// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/announcements": {
            "get": {
                "description": "获取全部公告列表，按创建时间倒序排列",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取后台公告列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.AdminAnnouncementResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一条新的后台公告",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "创建公告",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "公告信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAnnouncementUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAnnouncementResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/announcements/{id}": {
            "get": {
                "description": "根据公告ID获取后台公告详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取后台公告详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAnnouncementResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "根据公告ID更新后台公告",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "更新公告",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "公告信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAnnouncementUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAnnouncementResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据公告ID删除后台公告",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "删除公告",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/app-versions": {
            "get": {
                "description": "获取全部 App 版本列表，按平台升序、版本号降序排列",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取后台 App 版本列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.AdminAppVersionResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一条新的 App 版本记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "创建 App 版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "版本信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAppVersionUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAppVersionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/app-versions/{id}": {
            "get": {
                "description": "根据版本ID获取后台 App 版本详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取后台 App 版本详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAppVersionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "根据版本ID更新 App 版本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "更新 App 版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "版本信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAppVersionUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminAppVersionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据版本ID删除 App 版本",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "删除 App 版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "版本ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/semester-calendars": {
            "get": {
                "description": "获取全部校历列表，按学期代码倒序排列",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取后台校历列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.AdminSemesterCalendarResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一条新的后台校历",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "创建校历",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "校历信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminSemesterCalendarUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminSemesterCalendarResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/semester-calendars/{semester_code}": {
            "get": {
                "description": "根据学期代码获取后台校历详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取后台校历详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学期代码",
                        "name": "semester_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminSemesterCalendarResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "根据学期代码更新后台校历",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "更新校历",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学期代码",
                        "name": "semester_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "校历信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminSemesterCalendarUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminSemesterCalendarResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据学期代码删除后台校历",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "删除校历",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer admin token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学期代码",
                        "name": "semester_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "使用Token进行登录，如果用户不存在则自动注册。登录成功后返回含有JWT的凭证信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求，需包含获取的token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/announcements": {
            "get": {
                "description": "获取当前生效的公告列表，按创建时间倒序排列",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取公告列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.AnnouncementResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/app-versions": {
            "get": {
                "description": "获取指定平台的所有App版本历史",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取App所有版本",
                "parameters": [
                    {
                        "enum": [
                            "ios",
                            "android"
                        ],
                        "type": "string",
                        "description": "平台(ios或android)",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.AppVersionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/app-versions/check": {
            "get": {
                "description": "检查指定平台的App是否有更新",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "检查App版本更新",
                "parameters": [
                    {
                        "enum": [
                            "ios",
                            "android"
                        ],
                        "type": "string",
                        "description": "平台(ios或android)",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前版本号",
                        "name": "currentVersionCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CheckAppVersionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/campus-map": {
            "get": {
                "description": "获取GeoJSON格式的校园地图数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取校园地图数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CampusMapResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/semester-calendars": {
            "get": {
                "description": "获取所有校历的列表，按学期代码倒序排列",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取校历列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.SemesterCalendarListResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/semester-calendars/{semester_code}": {
            "get": {
                "description": "根据学期代码获取该学期的详细校历信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取校历详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "学期代码(如: 2024-2025-1)",
                        "name": "semester_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SemesterCalendarDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/task/electricity": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "同步电费定时推送任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "同步电费推送任务",
                "parameters": [
                    {
                        "description": "任务请求内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SyncElectricityTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "成功，无返回内容"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AdminAnnouncementResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isBanner": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.AdminAnnouncementUpsertRequest": {
            "type": "object",
            "required": [
                "content",
                "isActive",
                "isBanner",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isBanner": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.AdminAppVersionResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "downloadUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isForceUpdate": {
                    "type": "boolean"
                },
                "platform": {
                    "type": "string"
                },
                "releaseNotes": {
                    "type": "string"
                },
                "versionCode": {
                    "type": "integer"
                },
                "versionName": {
                    "type": "string"
                }
            }
        },
        "dto.AdminAppVersionUpsertRequest": {
            "type": "object",
            "required": [
                "downloadUrl",
                "isForceUpdate",
                "platform",
                "releaseNotes",
                "versionCode",
                "versionName"
            ],
            "properties": {
                "downloadUrl": {
                    "type": "string"
                },
                "isForceUpdate": {
                    "type": "boolean"
                },
                "platform": {
                    "type": "string",
                    "enum": [
                        "ios",
                        "android"
                    ]
                },
                "releaseNotes": {
                    "type": "string"
                },
                "versionCode": {
                    "type": "integer"
                },
                "versionName": {
                    "type": "string"
                }
            }
        },
        "dto.AdminSemesterCalendarResponse": {
            "type": "object",
            "properties": {
                "calendarEnd": {
                    "type": "string"
                },
                "calendarStart": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "customWeekRanges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CustomWeekRange"
                    }
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CalendarNote"
                    }
                },
                "semesterCode": {
                    "type": "string"
                },
                "semesterEnd": {
                    "type": "string"
                },
                "semesterStart": {
                    "type": "string"
                },
                "subtitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.AdminSemesterCalendarUpsertRequest": {
            "type": "object",
            "required": [
                "calendarEnd",
                "calendarStart",
                "semesterCode",
                "semesterEnd",
                "semesterStart",
                "subtitle",
                "title"
            ],
            "properties": {
                "calendarEnd": {
                    "type": "string"
                },
                "calendarStart": {
                    "type": "string"
                },
                "customWeekRanges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CustomWeekRange"
                    }
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CalendarNote"
                    }
                },
                "semesterCode": {
                    "type": "string"
                },
                "semesterEnd": {
                    "type": "string"
                },
                "semesterStart": {
                    "type": "string"
                },
                "subtitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.AnnouncementResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isBanner": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.AppVersionResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "downloadUrl": {
                    "type": "string"
                },
                "isForceUpdate": {
                    "type": "boolean"
                },
                "platform": {
                    "type": "string"
                },
                "releaseNotes": {
                    "type": "string"
                },
                "versionCode": {
                    "type": "integer"
                },
                "versionName": {
                    "type": "string"
                }
            }
        },
        "dto.CampusMapFeatureResponse": {
            "type": "object",
            "properties": {
                "geometry": {
                    "$ref": "#/definitions/model.FeatureGeometry"
                },
                "properties": {
                    "$ref": "#/definitions/model.FeatureProperties"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.CampusMapResponse": {
            "type": "object",
            "properties": {
                "features": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CampusMapFeatureResponse"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.CheckAppVersionResponse": {
            "type": "object",
            "properties": {
                "hasUpdate": {
                    "type": "boolean"
                },
                "isForceUpdate": {
                    "type": "boolean"
                },
                "latestVersion": {
                    "$ref": "#/definitions/dto.AppVersionResponse"
                }
            }
        },
        "dto.ElectricityTaskOption": {
            "type": "object",
            "required": [
                "building",
                "campus",
                "notifyTime",
                "room"
            ],
            "properties": {
                "building": {
                    "type": "string"
                },
                "campus": {
                    "type": "string"
                },
                "notifyTime": {
                    "type": "string"
                },
                "room": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "profile": {
                    "$ref": "#/definitions/sso.Profile"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.SemesterCalendarDetailResponse": {
            "type": "object",
            "properties": {
                "calendarEnd": {
                    "type": "string"
                },
                "calendarStart": {
                    "type": "string"
                },
                "customWeekRanges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CustomWeekRange"
                    }
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CalendarNote"
                    }
                },
                "semesterCode": {
                    "type": "string"
                },
                "semesterEnd": {
                    "type": "string"
                },
                "semesterStart": {
                    "type": "string"
                },
                "subtitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.SemesterCalendarListResponse": {
            "type": "object",
            "properties": {
                "semesterCode": {
                    "type": "string"
                },
                "subtitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.SyncElectricityTaskRequest": {
            "type": "object",
            "required": [
                "deviceToken"
            ],
            "properties": {
                "deviceToken": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ElectricityTaskOption"
                    }
                }
            }
        },
        "model.CalendarNote": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "needNumber": {
                    "type": "boolean"
                },
                "row": {
                    "type": "integer"
                }
            }
        },
        "model.CustomWeekRange": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "endRow": {
                    "type": "integer"
                },
                "startRow": {
                    "type": "integer"
                }
            }
        },
        "model.FeatureGeometry": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number",
                                "format": "float64"
                            }
                        }
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.FeatureProperties": {
            "type": "object",
            "properties": {
                "campus": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "sso.Profile": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "最终头像链接",
                    "type": "string"
                },
                "categoryName": {
                    "description": "学生类别",
                    "type": "string"
                },
                "certCode": {
                    "description": "身份证号（打码）",
                    "type": "string"
                },
                "defaultUserAvatar": {
                    "description": "默认头像链接",
                    "type": "string"
                },
                "deptName": {
                    "description": "学院名称",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "headImageIcon": {
                    "description": "用户设置的头像链接",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号（打码）",
                    "type": "string"
                },
                "userAccount": {
                    "description": "学号",
                    "type": "string"
                },
                "userName": {
                    "description": "姓名",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "go-csust-planet API",
	Description:      "go-csust-planet 项目的 API 接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
